name: Mi Primer Workflow

on:
    push:
      branches:
         - QA


jobs:
   ejemplo:
     runs-on: ubuntu-latest
     env:
       PLATAFORMA: "AWS"
       REGION: "US-EAST-1"
     steps:
       - name: Mostrar Plataforma solo si es AWS
         if: env.PLATAFORMA == 'AWS'
         run: echo "la plataforma es AWS" 


       
