name: Mi Primer Workflow

on:
    push:
      branches:
         - QA


jobs:
<<<<<<< HEAD
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test


       
=======
   ejemplo:
     runs-on: ubuntu-latest
     env:
       PLATAFORMA: "AWS"
       REGION: "US-EAST-1"
     steps:
       - name: Mostrar información de evento
         run: |
           echo "Repositorio ${{ github.repository }}"
           echo "Actor: ${{ github.hub }}"
           echo "Evento: ${{ github.event_name }}" 
>>>>>>> 92a7648dcfc293b9e414198eb18250e65fb83b4a
