name: Mi Primer Workflow

on:
    push:
      branches:
         - QA


jobs:
   ejemplo:
     runs-on: ubuntu-latest
     env:
       PLATAFORMA: "AWS"
       REGION: "US-EAST-1"
     steps:
       - name: Mostrar información de evento
         run: |
           echo "Repositorio ${{ github.repository }}"
           echo "Actor: ${{ github.hub }}"
           echo "Evento: ${{ github.event_name }}" 


       
